name: terraform-ci

on:
  pull_request:
    paths: ["terraform/**"]
  push:
    branches: ["main"]
    paths: ["terraform/**"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: terraform fmt
        run: terraform fmt -check -recursive

      - name: validate bootstrap
        working-directory: terraform/envs/bootstrap
        run: |
          terraform init -backend=false
          terraform validate

      - name: validate dev
        working-directory: terraform/envs/dev
        run: |
          terraform init -backend=false
          terraform validate
